
openapi: 3.0.0
info:
  title: You-DO API
  description: You-DOで使用するAPIの仕様書。
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: Hello
    description: APIの動作確認用のエンドポイント。
  - name: Sample-Post
    description: Spabaseの動作確認用のエンドポイント。
paths:
  /hello:
    get:
      tags:
        - Hello
      summary: Hello API
      description: APIの動作確認用のエンドポイント。
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello Next.js API Routes
  /sample-post:
    get:
      tags:
        - Sample-Post
      summary: Sample Post API
      description: Spabase動作確認用として、仮の投稿データを返すエンドポイント。
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    created_at:
                      type: string
                      example: 2021-08-01T00:00:00.000Z
                    title:
                      type: string
                      example: サンプルタイトル
                    body:
                      type: string
                      example: サンプル本文
